// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { all } from "./all.js";
import { allSettled } from "./allSettled.js";
import { any } from "./any.js";
import { create } from "./create.js";
import { debounce } from "./debounce.js";
import { defer } from "./defer.js";
import { is } from "./is.js";
import { limit } from "./limit.js";
import { orElse } from "./orElse.js";
import { queue } from "./queue.js";
import { reject } from "./reject.js";
import { resolve } from "./resolve.js";
import { then } from "./then.js";
import { throttle } from "./throttle.js";
import { wait } from "./wait.js";

export const Promise = {
    all,
    allSettled,
    any,
    create,
    debounce,
    defer,
    is,
    limit,
    orElse,
    queue,
    reject,
    resolve,
    then,
    throttle,
    wait,
}
